# Generated by Django 5.2.8 on 2025-11-20 01:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0002_alter_reserva_fecha_inicio_alter_sala_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='liberacion_programada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tiempo_liberacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
