# Generated by Django 5.2.8 on 2025-11-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0003_reserva_liberacion_programada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio_contador',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
